CREATE TABLE `tailorshop`.`customers`
 ( `id` INT(11) NOT NULL AUTO_INCREMENT , 
 	`lastName` TEXT NOT NULL ,
 	 `firstName` TEXT NOT NULL ,
 	  `address` VARCHAR(100) NOT NULL ,
 	   `type` TEXT NOT NULL ,
 	    `date` DATE NOT NULL , 
 	    `description` VARCHAR(150) NOT NULL , 
 	    `waist` FLOAT(3) NOT NULL ,
 	     `hip` FLOAT(3) NOT NULL , 
 	     `shoulder` FLOAT(3) NOT NULL ,
 	      `bust` FLOAT(3) NOT NULL , 
 	      `skirtLength` FLOAT(3) NOT NULL , 
 	      `gownLength` FLOAT(3) NOT NULL ,
 	       `shoulderToWaist` FLOAT(3) NOT NULL , 
 	       `acrossBack` FLOAT(3) NOT NULL ,
 	        `blouse` FLOAT(3) NOT NULL ,
 	         `underBust` FLOAT(3) NOT NULL ,
 	          `bp` FLOAT(3) NOT NULL ,
 	           `np` FLOAT(3) NOT NULL ,
 	            PRIMARY KEY (`id`)) ENGINE = InnoDB;